### ISSUE TITLE
Appveyor pipeline should install updated manifests

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2667]
Maintainers will have immediate response when updated manifests, have some mismatched hashes, extract_dir errors, ... ([one of failed pipelines because of hash mismatched](https://ci.appveyor.com/project/Ash258/scoop-ash258/builds/19732547#L193))

I implemented it in my bucket:
https://github.com/Ash258/scoop-Ash258/blob/master/Scoop-Bucket.Tests.ps1#L234-L287

And with artifacts pushing in appveyor.yml:

```yml
on_finish:
  - ps: |
      Push-AppveyorArtifact INSTALL.log
      Push-AppveyorArtifact TestResults.xml
```

After artifact push in yml, this line could be removed and `Invoke-Pester` could be run with `-EnableExit` (No need for result condition exit): 
https://github.com/lukesampson/scoop/blob/0c06e33c1a2525da00a1cbdf529a0403a1a25fff/test/bin/test.ps1#L51
