### ISSUE TITLE
running scoop on travis-ci on windows

### ISSUE THREAD

**Issue by prabirshrestha** [lukesampson/scoop#2936]
Took forever to get this working but hopefully someone will find this usueful. Might be worth adding an example in the docs?

https://github.com/prabirshrestha/vim-lsp/pull/225

```yaml
sudo: false
language: generic
git:
    depth: 3

matrix:
    include:
        - os: osx
        - os: linux
          dist: trusty
          python: "3.6"
        - os: windows
          language: shell

addons:
    apt:
        packages:
            - python3
            - python3-pip

before_install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="$HOME/Library/Python/3.6/bin:$PATH"; fi
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        pip3 install --user setuptools --upgrade;
        pip3 install --user vim-vint typing;
      elif  [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        powershell -Command "Set-ExecutionPolicy RemoteSigned -scope CurrentUser";
        powershell -Command "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')";
        export PATH="$HOME/scoop/shims:$PATH;"; 
        export PATH="$APPDATA/Python/Python37/Scripts:$PATH;";
        powershell -Command "scoop install python";
        python3 -m pip install --user vim-vint typing;
      fi

before_script:
    - uname -a
    - which -a vim
    - which -a python
    - vim --version

script:
    - vint autoload ftplugin plugin
```

 Might be worth convincing the travis CI folks to bundle scoop by default similar to chocolatey?

Feel free to close this issue.
