### ISSUE TITLE
Silent installation failures and forgetting buckets

### ISSUE THREAD

**Issue by tinydylan** [lukesampson/scoop#3568]
I'm provisioning windows VMs using Scoop. I'm invoking scoop using Ansible (connecting via WinRM). I run the sequence of commands below.

Sometimes, the Java installs silently fail. I suspect they can't find the extras bucket.

In my most recent build, `googlechrome` failed to install, but the command succeeded. When I logged into the VM after provisioning, `scoop bucket list` only showed the main and java bucket, not the extras bucket.

Something strange is happening with the buckets. A race condition, or some condition where the list of buckets gets messed up.

I'm not even sure how to debug it. Any help would be really appreciated!

```

- name: Install Scoop
  win_shell: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  become: no

- name: Update Scoop
  win_shell: scoop update
  become: no

- name: Update All Scoop Apps
  win_shell: scoop update '*'
  become: no

- name: Enable scoop "extras" bucket
  win_shell: scoop bucket add extras
  become: no

- name: Install lots of things
  win_shell: 'scoop install {{ item }}'
  with_items:
    - googlechrome
    - firefox
    - phantomjs
    - chromedriver
    - geckodriver
    - ie11webdriver
    - ant
    - dotnet
    - dotnet-sdk
    - dos2unix
    - git
    - jq
    - nuget
    - php
    - composer
    - openssh
    - wixtoolset
    - nodejs-lts
    - yarn
    - cygwin
  become: no

- name: Enable scoop "java" bucket
  win_shell: scoop bucket add java
  become: no

- name: Install some Javas
  win_shell: 'scoop install {{ item }}'
  with_items:
    - adopt12-hotspot
    - adopt11-hotspot
    - adopt10-hotspot
    - adopt9-hotspot
    - adopt8-hotspot
  become: no

- name: Default to Java 8
  win_shell: scoop reset adopt8-hotspot
  become: no
```
